#ifndef CRAYG_SRC_CRAYG_SRC_SCENE_PRIMITIVES_TRIANGLEMESH_PRIMVARS_PRIMVARTYPE_H_
#define CRAYG_SRC_CRAYG_SRC_SCENE_PRIMITIVES_TRIANGLEMESH_PRIMVARS_PRIMVARTYPE_H_

#include "utils/EnumUtils.h"

namespace crayg {

enum class PrimVarType { PER_FACE, PER_POINT, PER_VERTEX };

}

CRAYG_FMT_ENUM_FORMATTER(crayg::PrimVarType);

#endif // CRAYG_SRC_CRAYG_SRC_SCENE_PRIMITIVES_TRIANGLEMESH_PRIMVARS_PRIMVARTYPE_H_
