image: ubuntu:14.04

job:
  script:
  - apt-get update
  - apt-get install -y git g++ libc++-dev cmake clang gcovr
  - export CC=clang; export CXX=clang++
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - ./test/tests -o report.xml -r junit
