
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libgl1-mesa-dev
      - xorg-dev
      - libxcb-render-util0-dev
      - libxcb-xkb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-xinerama0-dev

matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      compiler: gcc
      before_script:
        - export CC=gcc-7
        - export CXX=g++-7
        - python --version
        - pip --version
        - pip install conan
        - chmod +x .travis/install.sh
        - ./.travis/install.sh
      env: GCC_VERSION=7
      python:
        "3.7"
    - os: osx
      language: cpp
      compiler: clang
      osx_image: xcode10
      before_script:
        - pip3 install conan

script:
  - conan remote list
  - python scripts/add_conan_remotes.py
  - conan remote list
  - conan user ci_github_actions -p -r=framebffr
  - conan install . --build missing
  - conan upload "*" --all --confirm -r=framebffr --parallel
  - cmake --version
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make -j 4
  - ctest -V
deploy:
  provider: releases
  api_key:
    secure: Vdpy9YFwLSYXyhl/id79K8qPrn9Jj0a5qwj+SOZ+DcfUDXnEgYtsuFipwnhtjO+cTkqF/rYJvtqsuI7j2BmYRysB55IH5M5w8dDMzDulB6criR0QsdtaxqjEyz2JPjyhjJYTgsYeoqlbbhON1P+to9cNQJZFIN0ksAJT9XruPz3fAFprhzg26EAdK/urLEzkLsJEEs3BPqJG/UULEiCYVEJoYZr0z2dnIHSfnmCuvJBF8Fa7xd5raFIILjoHnbR4M9dTxngXDICmZM0IT+SbCtSB6qJTIiYa3tYakMqe9r3jelSyM64hVlifdzh6+H7eW2qV4spU7WhA0uWmNCmgiqBqXcw3520ghLM9oANODta9bZ5p93cQ2fKl5PEFoi49WCls9U7Wnz3VF9ntdDBh9Qb1eQsSFgrRrJIrH9kuS34FS3/hLFMhhgcP3bCDaryWX4GVdvtWpV+7/P/+ADDaBAZd5pzy3TFonZkPaARratZYrDaPapgRlrxnlLgKY1Gkr/izN7V7KHRgIVCfiKRn6IrZXn35p29qLWwR9ncATU+GM8lBeDgE3Oi3/QVmxQtpKSpjKQ78+Zs8nmRlxcm0bU/um8WZVbRjYcQ2iA1TtoyoNgp8hTH0jpT+1clCBtAiQ8sxMxF5FH5UXSWXjNp0vgWIwmp9Q2XIUOV2iMlB7oA=
  file: build/standalone/crayg-standalone
  skip_cleanup: true
  on:
    repo: Latios96/crayg
    tags: true
