language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      before_script:
        - virtualenv venv
        - source venv/bin/activate
    - os: linux
      compiler: gcc
      before_script:
        - virtualenv venv
        - source venv/bin/activate
    - os: osx
      compiler: clang

script:
  - pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - maindir=$(pwd)
  - cd conan_packages/OpenImageIO
  - conan create . Latios/stable --build missing
  - cd ..
  - cd openexr
  - conan create . Latios/stable --build missing
  - cd $maindir
  - rm -rf build/
  - mkdir build
  - cd build
  - conan install .. --build missing
  - cmake ..
  - make -j 4
  - ./bin/tests
  - ./bin/crayg-standalone-tests
deploy:
  provider: releases
  api_key:
    secure: Vdpy9YFwLSYXyhl/id79K8qPrn9Jj0a5qwj+SOZ+DcfUDXnEgYtsuFipwnhtjO+cTkqF/rYJvtqsuI7j2BmYRysB55IH5M5w8dDMzDulB6criR0QsdtaxqjEyz2JPjyhjJYTgsYeoqlbbhON1P+to9cNQJZFIN0ksAJT9XruPz3fAFprhzg26EAdK/urLEzkLsJEEs3BPqJG/UULEiCYVEJoYZr0z2dnIHSfnmCuvJBF8Fa7xd5raFIILjoHnbR4M9dTxngXDICmZM0IT+SbCtSB6qJTIiYa3tYakMqe9r3jelSyM64hVlifdzh6+H7eW2qV4spU7WhA0uWmNCmgiqBqXcw3520ghLM9oANODta9bZ5p93cQ2fKl5PEFoi49WCls9U7Wnz3VF9ntdDBh9Qb1eQsSFgrRrJIrH9kuS34FS3/hLFMhhgcP3bCDaryWX4GVdvtWpV+7/P/+ADDaBAZd5pzy3TFonZkPaARratZYrDaPapgRlrxnlLgKY1Gkr/izN7V7KHRgIVCfiKRn6IrZXn35p29qLWwR9ncATU+GM8lBeDgE3Oi3/QVmxQtpKSpjKQ78+Zs8nmRlxcm0bU/um8WZVbRjYcQ2iA1TtoyoNgp8hTH0jpT+1clCBtAiQ8sxMxF5FH5UXSWXjNp0vgWIwmp9Q2XIUOV2iMlB7oA=
  file: build/standalone/crayg-standalone
  skip_cleanup: true
  on:
    repo: Latios96/crayg
    tags: true
