//
// Created by Jan on 13.05.2022.
//

#ifndef CRAYG_SRC_CRAYGUSD_SRC_CRAYGUSDBASE_H_
#define CRAYG_SRC_CRAYGUSD_SRC_CRAYGUSDBASE_H_

#define NOMINMAX

#endif //CRAYG_SRC_CRAYGUSD_SRC_CRAYGUSDBASE_H_
