#ifndef CRAYG_SRC_CRAYG_SRC_RENDERER_BUCKETSAMPLERS_BUCKETSAMPLERTYPE_H_
#define CRAYG_SRC_CRAYG_SRC_RENDERER_BUCKETSAMPLERS_BUCKETSAMPLERTYPE_H_
#include "utils/EnumUtils.h"

namespace crayg {

enum class BucketSamplerType { UNIFORM = 1, ADAPTIVE = 2 };

}

CRAYG_FMT_ENUM_FORMATTER(crayg::BucketSamplerType);

#endif // CRAYG_SRC_CRAYG_SRC_RENDERER_BUCKETSAMPLERS_BUCKETSAMPLERTYPE_H_
