#ifndef CRAYG_SRC_CRAYG_SRC_SCENE_CAMERA_LENSIO_LENSFILEFORMAT_H_
#define CRAYG_SRC_CRAYG_SRC_SCENE_CAMERA_LENSIO_LENSFILEFORMAT_H_

#include "utils/EnumUtils.h"

namespace crayg {

enum class LensFileFormat { TXT, JSON };

}

CRAYG_FMT_ENUM_FORMATTER(crayg::LensFileFormat);

#endif // CRAYG_SRC_CRAYG_SRC_SCENE_CAMERA_LENSIO_LENSFILEFORMAT_H_
