// clang-format off
#define CRAYG_CHECKD_NOT_NULLPTR(ptr) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_IS_VALID_INDEX(index, size) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_NOT_EQUALS(actual, notExpected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_GREATER_OR_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_GREATER_THAN(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_LESS_OR_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_LESS_THAN(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_IS_NOT_NAN(value) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_HAS_NO_NAN(value) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_STATE(actualState, expectedState) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_OPTIONAL_HAS_VALUE(optional) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_IS_NORMALIZED_VECTOR(vector) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_IS_EMPTY(obj) CRAYG_EMPTY_CHECK
#define CRAYG_CHECKD_IS_NOT_EMPTY(obj) CRAYG_EMPTY_CHECK
// clang-format on
