// clang-format off
#define CRAYGD_CHECK_NOT_NULLPTR(ptr) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_IS_VALID_INDEX(index, size) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_NOT_EQUALS(actual, notExpected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_GREATER_OR_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_GREATER_THAN(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_LESS_OR_EQUALS(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_LESS_THAN(actual, expected) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_NOT_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_NOT_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_IS_NOT_NAN(value) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_HAS_NO_NAN(value) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_STATE(actualState, expectedState) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_OPTIONAL_HAS_VALUE(optional) CRAYG_EMPTY_CHECK
#define CRAYGD_CHECK_IS_NORMALIZED_VECTOR(vector) CRAYG_EMPTY_CHECK
// clang-format on
