// clang-format off
#define CRAYG_CHECK_NOT_NULLPTR_IMPL(ptr) CRAYG_CHECK_OR_THROW(ptr != nullptr, fmt::format("{} should not be nullptr!", #ptr))
#define CRAYG_CHECK_IS_VALID_INDEX_IMPL(index, size) CRAYG_CHECK_OR_THROW((index >= 0 && index < size), fmt::format("Index {} is out of range: {}, size is {}!",#index, index, size))
#define CRAYG_CHECK_EQUALS_IMPL(actual, expected) CRAYG_CHECK_OR_THROW(actual == expected, fmt::format("Expected {} to be {}, was {}!", #actual, expected, actual))
#define CRAYG_CHECK_NOT_EQUALS_IMPL(actual, notExpected) CRAYG_CHECK_OR_THROW(actual != notExpected, fmt::format("Expected {} not to be {}, was {}!", #actual, notExpected, actual))
#define CRAYG_CHECK_GREATER_OR_EQUALS_IMPL(actual, expected) CRAYG_CHECK_OR_THROW((actual >= expected), fmt::format("Expected {} to be greater or equals than {}, was!", #actual, expected, actual))
#define CRAYG_CHECK_GREATER_THAN_IMPL(actual, expected) CRAYG_CHECK_OR_THROW((actual > expected), fmt::format("Expected {} to be greater than {}, was {}!", #actual, expected, actual))
#define CRAYG_CHECK_LESS_OR_EQUALS_IMPL(actual, expected) CRAYG_CHECK_OR_THROW((actual <= expected), fmt::format("Expected {} to be less or equals than {}, was!", #actual, expected, actual))
#define CRAYG_CHECK_LESS_THAN_IMPL(actual, expected) CRAYG_CHECK_OR_THROW((actual < expected), fmt::format("Expected {} to be less than {}, was {}!", #actual, expected, actual))
#define CRAYG_CHECK_WITHIN_RANGE_INCLUSIVE_IMPL(actual, min, max) CRAYG_CHECK_OR_THROW((actual >= min && actual <= max), fmt::format("Expected {} to be in interval [{},{}], value was {}!", #actual, min, max, actual))
#define CRAYG_CHECK_NOT_WITHIN_RANGE_INCLUSIVE_IMPL(actual, min, max) CRAYG_CHECK_OR_THROW((actual < min || actual > max), fmt::format("Expected {} not to be in interval [{},{}], value was {}!", #actual, min, max, actual))
#define CRAYG_CHECK_WITHIN_RANGE_EXCLUSIVE_IMPL(actual, min, max) CRAYG_CHECK_OR_THROW((actual > min && actual < max), fmt::format("Expected {} to be in interval ]{},{}[, was {}!", #actual, min, max, actual))
#define CRAYG_CHECK_NOT_WITHIN_RANGE_EXCLUSIVE_IMPL(actual, min, max) CRAYG_CHECK_OR_THROW((actual <= min || actual >= max), fmt::format("Expected {} not to be in interval ]{},{}[, was {}!", #actual, min, max, actual))
#define CRAYG_CHECK_IS_NOT_NAN_IMPL(value) CRAYG_CHECK_OR_THROW((!std::isnan(value)), fmt::format("{} should not be NaN!", #value))
#define CRAYG_CHECK_HAS_NO_NAN_IMPL(value) CRAYG_CHECK_OR_THROW((!value.hasNaN()), fmt::format("{} should not have NaN!", #value))
#define CRAYG_CHECK_STATE_IMPL(actualState, expectedState) CRAYG_CHECK_OR_THROW((actualState == expectedState), fmt::format("Expected {} to have state {}, was {}!", #actualState, actualState, expectedState))
#define CRAYG_CHECK_OPTIONAL_HAS_VALUE_IMPL(optional) CRAYG_CHECK_OR_THROW((optional.has_value()), fmt::format("{} has no value!", #optional))
#define CRAYG_CHECK_IS_NORMALIZED_VECTOR_IMPL(vector) CRAYG_CHECK_OR_THROW((std::fabs((vector).length() - 1) < 0.001f), fmt::format("{} is not unit vector!: {}", #vector, vector))
#define CRAYG_CHECK_IS_EMPTY_IMPL(obj) CRAYG_CHECK_OR_THROW(obj.empty(), fmt::format("{} should be empty!", #obj))
#define CRAYG_CHECK_IS_NOT_EMPTY_IMPL(obj) CRAYG_CHECK_OR_THROW((!obj.empty()), fmt::format("{} should not be empty!", #obj))
// clang-format on
