// clang-format off
#define CRAYG_CHECKD_NOT_NULLPTR(ptr) CRAYG_CHECK_NOT_NULLPTR_IMPL(ptr)
#define CRAYG_CHECKD_NOT_NULLPTR_F(ptr, formatStr, ...) CRAYG_CHECK_NOT_NULLPTR_IMPL_F(ptr, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_VALID_INDEX(index, size) CRAYG_CHECK_IS_VALID_INDEX_IMPL(index, size)
#define CRAYG_CHECKD_IS_VALID_INDEX_F(index, size, formatStr, ...) CRAYG_CHECK_IS_VALID_INDEX_IMPL_F(index, size, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_EQUALS(actual, expected) CRAYG_CHECK_EQUALS_IMPL(actual, expected)
#define CRAYG_CHECKD_EQUALS_F(actual, expected, formatStr, ...) CRAYG_CHECK_EQUALS_IMPL_F(actual, expected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_NOT_EQUALS(actual, notExpected) CRAYG_CHECK_NOT_EQUALS_IMPL(actual, notExpected)
#define CRAYG_CHECKD_NOT_EQUALS_F(actual, notExpected, formatStr, ...) CRAYG_CHECK_NOT_EQUALS_IMPL_F(actual, notExpected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_GREATER_OR_EQUALS(actual, expected) CRAYG_CHECK_GREATER_OR_EQUALS_IMPL(actual, expected)
#define CRAYG_CHECKD_GREATER_OR_EQUALS_F(actual, expected, formatStr, ...) CRAYG_CHECK_GREATER_OR_EQUALS_IMPL_F(actual, expected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_GREATER_THAN(actual, expected) CRAYG_CHECK_GREATER_THAN_IMPL(actual, expected)
#define CRAYG_CHECKD_GREATER_THAN_F(actual, expected, formatStr, ...) CRAYG_CHECK_GREATER_THAN_IMPL_F(actual, expected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_LESS_OR_EQUALS(actual, expected) CRAYG_CHECK_LESS_OR_EQUALS_IMPL(actual, expected)
#define CRAYG_CHECKD_LESS_OR_EQUALS_F(actual, expected, formatStr, ...) CRAYG_CHECK_LESS_OR_EQUALS_IMPL_F(actual, expected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_LESS_THAN(actual, expected) CRAYG_CHECK_LESS_THAN_IMPL(actual, expected)
#define CRAYG_CHECKD_LESS_THAN_F(actual, expected, formatStr, ...) CRAYG_CHECK_LESS_THAN_IMPL_F(actual, expected, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_CHECK_WITHIN_RANGE_INCLUSIVE_IMPL(actual, min, max)
#define CRAYG_CHECKD_WITHIN_RANGE_INCLUSIVE_F(actual, min, max, formatStr, ...) CRAYG_CHECK_WITHIN_RANGE_INCLUSIVE_IMPL_F(actual, min, max, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_INCLUSIVE(actual, min, max) CRAYG_CHECK_NOT_WITHIN_RANGE_INCLUSIVE_IMPL(actual, min, max)
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_INCLUSIVE_F(actual, min, max, formatStr, ...) CRAYG_CHECK_NOT_WITHIN_RANGE_INCLUSIVE_IMPL_F(actual, min, max, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_CHECK_WITHIN_RANGE_EXCLUSIVE_IMPL(actual, min, max)
#define CRAYG_CHECKD_WITHIN_RANGE_EXCLUSIVE_F(actual, min, max, formatStr, ...) CRAYG_CHECK_WITHIN_RANGE_EXCLUSIVE_IMPL_F(actual, min, max, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_EXCLUSIVE(actual, min, max) CRAYG_CHECK_NOT_WITHIN_RANGE_EXCLUSIVE_IMPL(actual, min, max)
#define CRAYG_CHECKD_NOT_WITHIN_RANGE_EXCLUSIVE_F(actual, min, max, formatStr, ...) CRAYG_CHECK_NOT_WITHIN_RANGE_EXCLUSIVE_IMPL_F(actual, min, max, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_NOT_NAN(value) CRAYG_CHECK_IS_NOT_NAN_IMPL(value)
#define CRAYG_CHECKD_IS_NOT_NAN_F(value, formatStr, ...) CRAYG_CHECK_IS_NOT_NAN_IMPL_F(value, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_HAS_NO_NAN(value) CRAYG_CHECK_HAS_NO_NAN_IMPL(value)
#define CRAYG_CHECKD_HAS_NO_NAN_F(value, formatStr, ...) CRAYG_CHECK_HAS_NO_NAN_IMPL_F(value, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_STATE(actualState, expectedState) CRAYG_CHECK_STATE_IMPL(actualState, expectedState)
#define CRAYG_CHECKD_STATE_F(actualState, expectedState, formatStr, ...) CRAYG_CHECK_STATE_IMPL_F(actualState, expectedState, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_OPTIONAL_HAS_VALUE(optional) CRAYG_CHECK_OPTIONAL_HAS_VALUE_IMPL(optional)
#define CRAYG_CHECKD_OPTIONAL_HAS_VALUE_F(optional, formatStr, ...) CRAYG_CHECK_OPTIONAL_HAS_VALUE_IMPL_F(optional, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_NORMALIZED_VECTOR(vector) CRAYG_CHECK_IS_NORMALIZED_VECTOR_IMPL(vector)
#define CRAYG_CHECKD_IS_NORMALIZED_VECTOR_F(vector, formatStr, ...) CRAYG_CHECK_IS_NORMALIZED_VECTOR_IMPL_F(vector, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_EMPTY(obj) CRAYG_CHECK_IS_EMPTY_IMPL(obj)
#define CRAYG_CHECKD_IS_EMPTY_F(obj, formatStr, ...) CRAYG_CHECK_IS_EMPTY_IMPL_F(obj, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_NOT_EMPTY(obj) CRAYG_CHECK_IS_NOT_EMPTY_IMPL(obj)
#define CRAYG_CHECKD_IS_NOT_EMPTY_F(obj, formatStr, ...) CRAYG_CHECK_IS_NOT_EMPTY_IMPL_F(obj, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_WITHIN_BOUNDS(point, bounds) CRAYG_CHECK_IS_WITHIN_BOUNDS_IMPL(point, bounds)
#define CRAYG_CHECKD_IS_WITHIN_BOUNDS_F(point, bounds, formatStr, ...) CRAYG_CHECK_IS_WITHIN_BOUNDS_IMPL_F(point, bounds, formatStr __VA_OPT__(,) __VA_ARGS__)
#define CRAYG_CHECKD_IS_NOT_WITHIN_BOUNDS(point, bounds) CRAYG_CHECK_IS_NOT_WITHIN_BOUNDS_IMPL(point, bounds)
#define CRAYG_CHECKD_IS_NOT_WITHIN_BOUNDS_F(point, bounds, formatStr, ...) CRAYG_CHECK_IS_NOT_WITHIN_BOUNDS_IMPL_F(point, bounds, formatStr __VA_OPT__(,) __VA_ARGS__)
// clang-format on
