static const char *lens_name = "double gauss angenieux 50mm";     // descriptive name of the lens
static const float lens_outer_pupil_radius = 27.000000;           // scene facing radius in mm
static const float lens_inner_pupil_radius = 13.500000;           // sensor facing radius in mm
static const float lens_length = 32.080002;                       // overall lens length in mm
static const float lens_focal_length = 7.830000;                  // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 32.080002;                 // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 0.000000;       // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 82.099998; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.078379; // cosine of the approximate field of view assuming a 35mm image
