
#ifndef CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_
#define CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_

namespace crayg {

enum class IntegratorType { RAYTRACING = 1, DEBUG = 2 };

}

#endif //CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_
