#ifndef CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_
#define CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_

#include "utils/EnumUtils.h"

namespace crayg {

enum class IntegratorType { RAYTRACING = 1, DEBUG = 2, AMBIENT_OCCLUSION = 3 };

}

CRAYG_FMT_ENUM_FORMATTER(crayg::IntegratorType);

#endif // CRAYG_SRC_CRAYG_SRC_INTEGRATORS_INTEGRATORTYPE_H_
