#ifndef CRAYG_SRC_CRAYG_SRC_IMAGE_IMAGEITERATORS_BUCKETS_BUCKETSEQUENCETYPE_H_
#define CRAYG_SRC_CRAYG_SRC_IMAGE_IMAGEITERATORS_BUCKETS_BUCKETSEQUENCETYPE_H_

#include "utils/EnumUtils.h"

namespace crayg {

enum class BucketSequenceType { LINE_BY_LINE = 1, SPIRAL = 2 };

}

CRAYG_FMT_ENUM_FORMATTER(crayg::BucketSequenceType);

#endif // CRAYG_SRC_CRAYG_SRC_IMAGE_IMAGEITERATORS_BUCKETS_BUCKETSEQUENCETYPE_H_
