name: Github Actions CI

on: [push]

jobs:
  build-windows:
    name:  windows-2016
    runs-on:  windows-2016

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      name: Cache Conan user packages
      with:
        path: ~/.conan/
        key: ${{ runner.os }}-conan-user-${{ hashFiles('~/.conan/') }}
        restore-keys: |
          ${{ runner.os }}-conan-user-
    - uses: actions/cache@v1
        name: Cache Conan packages
        with:
          path: C:/.conan
          key: ${{ runner.os }}-conan-${{ hashFiles('C:/.conan') }}
          restore-keys: |
            ${{ runner.os }}-conan-
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install conan
      run: |
        pip install conan
        conan --version
    - name: add bincrafters remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan -f
    - name: add ppodsiadly remote
      run: conan remote add ppodsiadly https://api.bintray.com/conan/ppodsiadly/conan -f
    - name: prepare build
      run: mkdir build
    - name: run CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      working-directory: build
      run : cmake --build . --config Release
    - name: run tests
      working-directory: build
      run: ctest -C Release -V
