name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install conan
      run: pip3 install conan
    - name: add bincrafters remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan -f
    - name: add ppodsiadly remote
      run: conan remote add ppodsiadly https://api.bintray.com/conan/ppodsiadly/conan -f
    - name: create build folder
      run: |
        mkdir build
        cd build
    - name: run CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: run make
      run : make -j 4
    - name: run tests
      run: ctest -V
