name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install conan
      run: |
        pip install conan
        conan --version
    - name: add bincrafters remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan -f
    - name: add ppodsiadly remote
      run: conan remote add ppodsiadly https://api.bintray.com/conan/ppodsiadly/conan -f
    - name: prepare build
      run: mkdir build
    - name: run CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: run make
      working-directory: build
      run : make -j 4
    - name: run tests
      working-directory: build
      run: ctest -V
