name: Github Actions CI

on: [push]

jobs:
  build-windows:
    name:  windows-2016
    runs-on:  windows-2016
    env:
      CONAN_USER_HOME: C:/conan_user_home
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache Conan user packages
      with:
        path: C:/conan_user_home
        key: conan-user-packages-windows-2016-2
    - uses: actions/cache@v2
      name: Cache Conan packages
      with:
        path: C:/.conan
        key: windows-2016-conan-packages-2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install conan
      run: |
        pip install conan
        conan --version
    - name: add remotes
      run: |
        conan remote list
        python scripts/add_conan_remotes.py
        conan remote list
    - name: conan login
      run: conan user ci_github_actions -p -r=framebffr
      env:
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
    - name: build dependencies
      run: conan install . --build missing
    - name: upload dependencies
      run: conan upload * --all --confirm -r=framebffr --parallel
    - name: prepare build
      run: mkdir build
    - name: run CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      shell: cmd
    - name: build
      working-directory: build
      run : cmake --build . --config Release
      shell: cmd
    - name: run tests
      working-directory: build
      run: ctest -C Release -V
      shell: cmd
